<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\detective.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="assets\images\" />
    <Folder Include="Templates\" />
  </ItemGroup>
  <ItemGroup>
    <!-- pick up all generated XAML code-behind files -->
    <Compile Include="obj\$(Configuration)\$(TargetFramework)\**\*.g.cs" />
  </ItemGroup>


</Project>